_format_version: "3.0"
_transform: true

services:
  - name: frontend
    url: ${FRONTEND_PUBLIC_URL:-http://frontend:3000}
    routes:
      - name: root
        paths:
          - /
        strip_path: false
  - name: core
    url: http://core-go:8080
    routes:
      - name: api
        paths:
          - /api
        strip_path: false

plugins:
  - name: correlation-id
    config:
      header_name: x-request-id
