FROM golang:1.22-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o /bin/core

FROM alpine:3.19
RUN apk add --no-cache ca-certificates wget
COPY --from=builder /bin/core /bin/core
EXPOSE 8080
ENTRYPOINT ["/bin/core"]
